[general]
seed = 42
sampling_seed = 42
train_dataset_seed = 42
val_dataset_seed = 42
normalize_embeddings = true
mixed_precision = 'no'
weight_init = 'orthogonal'
dataset = 'nq'
max_seq_length = 64
unsup_emb = 'gte'
sup_emb = 'gtr'
n_embs_per_batch = 1
finetune_mode = false
noise_level = 0.0
num_points = 100000
epochs = 10

[translator]
style = 'shared_ae'
norm_style = 'layer'
depth = 6
transform_depth = 10
d_adapter = 768
d_hidden = 768
d_transform = 512 
n_embs_per_batch = 1
use_small_output_adapters = false
use_residual_adapters = true
d_z = 512

[discriminator]
gan_style = "vanilla"
disc_depth = 2
disc_dim = 512
use_residual = true

[train]
bs = 1024
gradient_accumulation_steps = 2
lr = 1e-3
no_scheduler = false
max_grad_norm = 1000.0
loss_coefficient_reverse_rec = 0.0
loss_coefficient_rec = 1.0
loss_coefficient_vsp = 1.0
loss_coefficient_cc_trans = 10.0
loss_coefficient_cc_rec = 10.0
loss_coefficient_cc_vsp = 10.0
loss_coefficient_r1_penalty = 0.0
warmup_length = 4000

patience = 3
min_delta = 0.0
min_epochs = 10
lambda_rec  = 1.0
lambda_cyc  = 1.0
lambda_dist = 0.0
lambda_stab = 0.1
lambda_geo  = 0.0
sinkhorn_eps = 0.1

[gan]
disc_lr = 2e-5
eps = 6.25e-10
smooth = 0.9
loss_coefficient_disc = 1.0
loss_coefficient_gen = 1.0
loss_coefficient_latent_gen = 1.0
loss_coefficient_similarity_gen = 0.0

[eval]
val_size = 4096
val_bs = 1024
top_k_size = 1024
top_k_batches = 4
k = 16
heatmap_size = 64

[logging]
use_wandb = true
wandb_project = 'projection-SAE-rec_only'
wandb_name = 'shared_ae_testing'
load_dir = './runs/'
save_dir = './runs/{}/'
force_dump = true
